proba_threshold: 0.5

models:
  - name: xgb
    classifier: xgboost.XGBClassifier
    params:
        n_estimators: [900]
        max_depth: [15]
        learning_rate: [0.05]
        subsample: [0.7]
        tree_method: ["hist"]
        colsample_bytree: [0.5]
        subsample: [0.5]
        min_child_weight: [0.3]
        gamma: [0.1]
        n_jobs: [-1]
  - name: lgbm
    classifier: lightgbm.LGBMClassifier
    params:
        n_estimators: [900]
        max_depth: [12]
        num_leaves: [127]
        learning_rate: [0.005, 0.05]
        feature_fraction: [0.75]
        bagging_fraction: [0.8]
        bagging_freq: [10]
        min_child_weight: [0.3]
        n_jobs: [-1]
  - name: rf
    classifier: sklearn.ensemble.RandomForestClassifier
    params:
        n_estimators: [400]
        max_depth: [15]
        min_samples_leaf: [4]
        n_jobs: [-1]
